%% simulate_dashboard_input.
% Quick notepad for simulating tile inputs from the dashboard to
% qualityControl. Uses the AVGs generated by generateAVGs.

%% Parameters
inputFolder = 'Y:\mousebrainmicro\data\Dashboard training set\2016-02-21\'; %Location of generated averages.
microscopeFile = 'Y:\mousebrainmicro\acquisition\2016-02-21\2016-02-21\00\00033\00033-ngc.microscope'; % fixed location of micrscope file.
bufferSize = 500; %frame size of each AVG stack.
displayRange = [11000,23000]; % as percentile value.
%% Output window.
hFig = figure('Position',[400,400,700,900],'Name','Quality control test');
hAx = axes('Position',[0.05,0.075,0.9,0.9]);
hIm = [];
info.lowBox = uicontrol('Style', 'edit', 'String', num2str(displayRange(1)),...
    'Position', [20 10 50 25],...
    'FontSize', 9); 
info.highBox = uicontrol('Style', 'edit', 'String', num2str(displayRange(2)),...
    'Position', [120 10 50 25],...
    'FontSize', 9); 

%% Go through tiles.
for iTile = 1:1500
   % Prep tile loc.
   cFile = (floor(iTile/bufferSize)*bufferSize)+bufferSize;
   cFile = fullfile(inputFolder,sprintf('%i.tif',cFile)); % File from which to read.
   cFrame = mod(iTile,bufferSize); % frame in file.
   
   I = imread(cFile,cFrame);
   if isempty(hIm)
       hIm = imshow(I,[str2double(info.lowBox.String), str2double(info.highBox.String)]);
   else
       hIm.CData = I;
       hAx.CLim = [str2double(info.lowBox.String),str2double(info.highBox.String)];
   end
   drawnow
end
